### ISSUE TITLE
Remove testrpc dependency

### ISSUE THREAD

**Issue by pipermerriam** [raineorshine/solidity-repl#1]
I think you can remove the dependency on `testrpc` pretty easily and interact with a js based ethereum EVM directly.

I'd recommend looking into the `ethereum-vm` package.  You can probably steal most of the functionality from https://github.com/ethereumjs/testrpc/blob/master/lib/manager.js

**Comment by pelle** [comment]
You can also use it internally like a library pretty easily:

https://github.com/ethereumjs/testrpc#library

**Comment by redsquirrel** [comment]
Yep, seems like you should be able to get away with not having to start it
as a separate process.

**Comment by raineorshine** [comment]
Done
