### ISSUE TITLE
Disable warnings when executing commands 

### ISSUE THREAD

**Issue by tina1998612** [raineorshine/solidity-repl#15]
How can I disable the following warnings and have only the nice output? I'm using macOS High Serria. Thanks!!
![screen shot 2018-01-02 at 10 52 17 am](https://user-images.githubusercontent.com/19768276/34473249-4d7cb65a-efab-11e7-8d05-fbe8b091c138.png)

**Comment by raineorshine** [comment]
Good catch! That was introduced with the new Solidity version.

I fixed the issue in v0.4.0. Trying updating!

**Comment by tina1998612** [comment]
Thanks so much for the swift response! The warnings are all gone.

One last problem, there is an unknown output "undefined" right after the initial prompt like this:
![screen shot 2018-01-04 at 10 50 28 am](https://user-images.githubusercontent.com/19768276/34548567-c50d8170-f13d-11e7-8bf2-ecb6dc47a890.png)

Thanks!!

**Comment by raineorshine** [comment]
Oh thanks! I left in a console.log :). Should be fixed now!
